title: Machine Learning Fundamentals - CS 4501
description: Fall 2025 course website following "Hands-on Machine Learning"
# theme: jekyll-theme-minimal
remote_theme: alshedivat/al-folio
# remote_theme: just-the-docs/just-the-docs  # Example for Just the Docs
plugins:
  - jekyll-remote-theme
